// This file is generated by the corba.js IDL compiler from '/Users/mark/c/mediapipe/test/makehuman.idl'.

#pragma once
#include "../src/corba/orb.hh"
#include "../src/corba/giop.hh"
#include "../src/corba/coroutine.hh"
#include <string>
#include <vector>

class Backend {
public:
    virtual CORBA::task<std::string> hello(std::string hello) = 0;
    virtual CORBA::task<void> fail() = 0;
};

