// This file is generated by the corba.js IDL compiler from 'makehuman.idl'.

#pragma once
#include <corba/orb.hh>
#include <corba/giop.hh>
#include <corba/coroutine.hh>
#include <string>
#include <vector>

class Backend {
public:
    virtual CORBA::async<std::string> hello(const std::string_view & hello) = 0;
    virtual CORBA::async<void> fail() = 0;
    static std::shared_ptr<Backend> _narrow(std::shared_ptr<CORBA::Object> pointer);
};

class Backend2 {
public:
    virtual void chordata(bool on) = 0;
    virtual void mediapipe(bool on) = 0;
    static std::shared_ptr<Backend2> _narrow(std::shared_ptr<CORBA::Object> pointer);
};

