interface Interface {
    boolean callBoolean(in boolean value);
    octet callOctet(in octet value);
    unsigned short callUShort(in unsigned short value);
    unsigned long callUnsignedLong(in unsigned long value);
    unsigned long long callUnsignedLongLong(in unsigned long long value);
    string callString(in string value);
}; 
