interface Peer {
    string callString(in string value);
};

interface Interface {
    boolean callBoolean(in boolean value);
    octet callOctet(in octet value);
    unsigned short callUShort(in unsigned short value);
    unsigned long callUnsignedLong(in unsigned long value);
    unsigned long long callUnsignedLongLong(in unsigned long long value);
    string callString(in string value);
    sequence<octet> callBlob(in sequence<octet> value);
    void setPeer(in Peer peer);
    string callPeer(in string value);
}; 
